name: Deploy Docker staging image

on:
  push:
    branches:
      - 'Staging'

  workflow_dispatch:

jobs:
  build_and_deploy_alpha_image:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./tiktaktoe_server/
          file: ./tiktaktoe_server/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/tiktaktoe_server:alpha
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/tiktaktoe_server:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/tiktaktoe_server:buildcache,mode=max

      -
        name: Deploy image to server
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.OTOMA_SERVER_ADDR }}
          username: ${{ secrets.OTOMA_SERVER_USER }}
          password: ${{ secrets.OTOMA_SERVER_PASSWORD }}
          script: |
            docker rm $(docker stop $(docker ps -a -q --filter ancestor=wolfgear/tiktaktoe_server:alpha))
            docker rmi wolfgear/tiktaktoe_server:alpha
            docker pull wolfgear/tiktaktoe_server:alpha
            docker run -p 8098:8090 -d wolfgear/tiktaktoe_server:alpha


